{
 "title": "Docker Prometheus Monitoring",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus, ",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Host Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Targets Online",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total[1m] ) )) / count(node_cpu_seconds_total{mode=\"system\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes - container_fs_usage_bytes) / sum(container_fs_limit_bytes)"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device!~\"lo\"}",
     "legendFormat": "{{job}}-recv"
    },
    {
     "expr": "node_network_transmit_bytes_total{device!~\"lo\"}",
     "legendFormat": "{{job}}-sent"
    }
   ]
  },
  {
   "title": "Node Mermory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"Qed0-HostMetrics\"}",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes{job=\"Qed0-HostMetrics\"})",
     "legendFormat": "Used Qed0"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes{job=\"Qed1-HostMetrics\"})",
     "legendFormat": "Used Qed1"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes{job=\"Qed2-HostMetrics\"})",
     "legendFormat": "Used Qed2"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {job=~\"Qed0-HostMetrics\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes{job=~\"Qed0-HostMetrics\"}) ",
     "legendFormat": "Used-Qed0"
    },
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes{job=~\"Qed1-HostMetrics\"})",
     "legendFormat": "Used-Qed1"
    },
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes{job=~\"Qed2-HostMetrics\"})",
     "legendFormat": "Used-Qed2"
    }
   ]
  },
  {
   "title": "Container Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "container_cpu_load_average_10s{image!=\"\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_max_usage_bytes{image!=\"\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 13, "w": 10, "x": 12, "y": 24 },
     "targets": [
      { "expr": "ALERTS" }
     ]
    },
    {
     "title": "Container Network Input",
     "type": "graph",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m] ) ))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Container Network Output",
     "type": "graph",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m] ) ))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Running Versions",
     "type": "table",
     "gridPos": { "h": 10, "w": 10, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "cadvisor_version_info",
       "legendFormat": "cAdvisor  Version: {{cadvisorVersion}}"
      },
      {
       "expr": "prometheus_build_info",
       "legendFormat": "Prometheus Version: {{version}}"
      },
      {
       "expr": "node_exporter_build_info",
       "legendFormat": "Node-Exporter Version: {{version}}"
      }
     ]
    }
   ]
  }
 ]
}