{
 "title": "QED",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "query": "5s,15s,30s,1m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances running",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(qed_instances_count)", "legendFormat": "QEDs" },
    {
     "expr": "sum(qed_sender_instances_count)",
     "legendFormat": "senders"
    },
    {
     "expr": "sum(qed_auditor_instances_count)",
     "legendFormat": "auditors"
    },
    {
     "expr": "sum(qed_monitor_instances_count)",
     "legendFormat": "monitors"
    },
    {
     "expr": "sum(qed_publisher_instances_count)",
     "legendFormat": "publishers"
    },
    { "expr": "sum(qed_store_instances_count)", "legendFormat": "store" }
   ]
  },
  {
   "title": "Adds",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(qed_balloon_add_total) / sum(qed_instances_count)"
    }
   ]
  },
  {
   "title": "Membership",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(qed_balloon_membership_total) + sum(qed_balloon_digest_membership_total)"
    }
   ]
  },
  {
   "title": "Incremental",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(qed_balloon_incremental_total)"
    }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Add",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_balloon_add_total[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Membership",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_balloon_membership_total[$interval])) by (job)",
     "legendFormat": "{{job}}-memb"
    },
    {
     "expr": "sum(rate(qed_balloon_digest_membership_total[$interval])) by (job)",
     "legendFormat": "{{job}}-digest_memb"
    }
   ]
  },
  {
   "title": "Incremental",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_balloon_incremental_total[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Batches sent by Sender",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_sender_batches_sent_total[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Auditor batches received",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(qed_auditor_batches_received_total)"
    }
   ]
  },
  {
   "title": "Monitor batches received",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 26 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(qed_monitor_batches_received_total)"
    }
   ]
  },
  {
   "title": "Publisher batches received",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 26 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(qed_publisher_batches_received_total)"
    }
   ]
  },
  {
   "title": "Batches received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_monitor_batches_received_total{job=~\"Monitor.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(rate(qed_auditor_batches_received_total{job=~\"Auditor.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(rate(qed_publisher_batches_received_total{job=~\"Publisher.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Batches process duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_monitor_batches_process_seconds{job=~\"Monitor.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(rate(qed_auditor_batches_process_seconds{job=~\"Auditor.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(rate(qed_publisher_batches_process_seconds{job=~\"Publisher.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Batches stored",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(qed_store_batches_stored_total)"
    }
   ]
  },
  {
   "title": "Snapshots retrieved",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "qed_store_snapshots_retrieved_total",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(qed_store_alerts_generated_total)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}