{
 "title": "Cache Data, Filter, Index",
 "description": "Break-down of Cache ops by Data, Filter and Index",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "storage, wal" }
  ]
 },
 "panels": [
  {
   "title": "Block cache data hit, miss and add",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[instance]]_block_cache_data_hit) by (job)",
     "legendFormat": "hit_{{job}}"
    },
    {
     "expr": "sum(qed_[[instance]]_block_cache_data_miss) by (job)",
     "legendFormat": "miss_{{job}}"
    },
    {
     "expr": "sum(qed_[[instance]]_block_cache_data_add) by (job)",
     "legendFormat": "add_{{job}}"
    }
   ]
  },
  {
   "title": "Block cache data bytes inserted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[instance]]_block_cache_data_bytes_insert) by (job)",
     "legendFormat": "bytes_inserted_{{job}}"
    }
   ]
  },
  {
   "title": "Block cache filter hit, miss and add",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[instance]]_block_cache_filter_hit) by (job)",
     "legendFormat": "hit_{{job}}"
    },
    {
     "expr": "sum(qed_[[instance]]_block_cache_filter_miss) by (job)",
     "legendFormat": "miss_{{job}}"
    },
    {
     "expr": "sum(qed_[[instance]]_block_cache_filter_add) by (job)",
     "legendFormat": "add_{{job}}"
    }
   ]
  },
  {
   "title": "Block cache filter bytes inserted and evicted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[instance]]_block_cache_filter_bytes_insert) by (job)",
     "legendFormat": "bytes_inserted_{{job}}"
    },
    {
     "expr": "sum(qed_[[instance]]_block_cache_filter_bytes_evict) by (job)",
     "legendFormat": "bytes_evicted_{{job}}"
    }
   ]
  },
  {
   "title": "Block cache index hit, miss and add",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[instance]]_block_cache_index_hit) by (job)",
     "legendFormat": "hit_{{job}}"
    },
    {
     "expr": "sum(qed_[[instance]]_block_cache_index_miss) by (job)",
     "legendFormat": "miss_{{job}}"
    },
    {
     "expr": "sum(qed_[[instance]]_block_cache_index_add) by (job)",
     "legendFormat": "add_{{job}}"
    }
   ]
  },
  {
   "title": "Block cache index bytes inserted and evicted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[instance]]_block_cache_index_bytes_insert) by (job)",
     "legendFormat": "bytes_inserted_{{job}}"
    },
    {
     "expr": "sum(qed_[[instance]]_block_cache_index_bytes_evict) by (job)",
     "legendFormat": "bytes_evicted_{{job}}"
    }
   ]
  }
 ]
}