{
 "title": "QED",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "5s,15s,30s,1m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(qed_server_instances)", "legendFormat": "QEDs" },
    {
     "expr": "sum(qed_sender_instances_count)",
     "legendFormat": "senders"
    },
    {
     "expr": "sum(qed_auditor_instances_count)",
     "legendFormat": "auditors"
    },
    {
     "expr": "sum(qed_monitor_instances_count)",
     "legendFormat": "monitors"
    },
    {
     "expr": "sum(qed_publisher_instances_count)",
     "legendFormat": "publishers"
    },
    { "expr": "sum(qed_store_instances_count)", "legendFormat": "store" }
   ]
  },
  {
   "title": "Current Version @ Qed0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "qed_raft_balloon_version{job=\"Qed0\"}",
     "legendFormat": "version-{{job}}"
    }
   ]
  },
  {
   "title": "Adds @ Qed0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "qed_raft_balloon_adds{job=\"Qed0\"}"
    }
   ]
  },
  {
   "title": "Membership @ Qed0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "qed_raft_balloon_digest_membership_queries{job=\"Qed0\"}"
    }
   ]
  },
  {
   "title": "Incremental @ Qed0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "qed_raft_balloon_incremental_queries{job=\"Qed0\"}"
    }
   ]
  },
  {
   "title": "Current Version @ Qed1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "qed_raft_balloon_version{job=\"Qed1\"}",
     "legendFormat": "version-{{job}}"
    }
   ]
  },
  {
   "title": "Adds @ Qed1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "qed_raft_balloon_adds{job=\"Qed1\"}"
    }
   ]
  },
  {
   "title": "Membership @ Qed1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "qed_raft_balloon_digest_membership_queries{job=\"Qed1\"}"
    }
   ]
  },
  {
   "title": "Incremental @ Qed1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "qed_raft_balloon_incremental_queries{job=\"Qed1\"}"
    }
   ]
  },
  {
   "title": "Current Version @ Qed2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "qed_raft_balloon_version{job=\"Qed2\"}",
     "legendFormat": "version-{{job}}"
    }
   ]
  },
  {
   "title": "Adds @ Qed2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "qed_raft_balloon_adds{job=\"Qed2\"}"
    }
   ]
  },
  {
   "title": "Membership @ Qed2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "qed_raft_balloon_digest_membership_queries{job=\"Qed2\"}"
    }
   ]
  },
  {
   "title": "Incremental @ Qed2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "qed_raft_balloon_incremental_queries{job=\"Qed2\"}"
    }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Add",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_raft_balloon_adds[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Membership",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_raft_balloon_digest_membership_queries[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Incremental",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_raft_balloon_incremental_queries[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Batches sent by Sender",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_sender_batches_sent_total[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Auditor batches received",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(qed_auditor_batches_received_total)"
    }
   ]
  },
  {
   "title": "Auditor err",
   "type": "singlestat",
   "description": "Auditor failed to get membership proof",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qed_auditor_get_membership_proof_err_total)"
    }
   ]
  },
  {
   "title": "Monitor batches received",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 27 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(qed_monitor_batches_received_total)"
    }
   ]
  },
  {
   "title": "Monitor err",
   "type": "singlestat",
   "description": "Monitor failed to get incremental proof",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qed_monitor_get_incremental_proof_err_total)"
    }
   ]
  },
  {
   "title": "Publisher batches received",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(qed_publisher_batches_received_total)"
    }
   ]
  },
  {
   "title": "Batches received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_monitor_batches_received_total{job=~\"Monitor.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(rate(qed_auditor_batches_received_total{job=~\"Auditor.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(rate(qed_publisher_batches_received_total{job=~\"Publisher.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Batches process duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qed_monitor_batches_process_seconds{job=~\"Monitor.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(rate(qed_auditor_batches_process_seconds{job=~\"Auditor.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(rate(qed_publisher_batches_process_seconds{job=~\"Publisher.*\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Batches stored",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(qed_store_batches_stored_total)"
    }
   ]
  },
  {
   "title": "Snapshots stored",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 42 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(qed_store_events_stored_total)"
    }
   ]
  },
  {
   "title": "Snapshots retrieved",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 42 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "qed_store_snapshots_retrieved_total",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}