{
 "title": "RocksDBTables",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "label": "Table",
    "query": "storage_cf_hyper, storage_cf_history, storage_cf_fsm, wal_cf_log, wal_cf_stable"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of files by level",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[table]]_num_files_at_level_0) by (job)",
     "legendFormat": "level0-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_num_files_at_level_1) by (job)",
     "legendFormat": "level1-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_num_files_at_level_2) by (job)",
     "legendFormat": "level2-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_num_files_at_level_3) by (job)",
     "legendFormat": "level3-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_num_files_at_level_4) by (job)",
     "legendFormat": "level4-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_num_files_at_level_5) by (job)",
     "legendFormat": "level5-{{job}}"
    }
   ]
  },
  {
   "title": "Number of immutable memtables",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[table]]_num_immutable_memtables) by (job)",
     "legendFormat": "not_flushed-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_num_immutable_memtables_flushed) by (job)",
     "legendFormat": "flushed-{{job}}"
    }
   ]
  },
  {
   "title": "Running flushes and compactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[table]]_num_running_flushes) by (job)",
     "legendFormat": "flushes-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_num_running_compactions) by (job)",
     "legendFormat": "compactions-{{job}}"
    }
   ]
  },
  {
   "title": "memtable size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[table]]_cur_size_active_memtable) by (job)",
     "legendFormat": "active-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_cur_size_all_memtables) by (job)",
     "legendFormat": "active-unflushed-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_size_all_memtables) by (job)",
     "legendFormat": "active-unflushed-pinned-{{job}}"
    }
   ]
  },
  {
   "title": "Number of entries in memtables",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[table]]_num_entries_active_memtable) by (job)",
     "legendFormat": "active-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_num_entries_imm_memtables) by (job)",
     "legendFormat": "unflushed-immutable-{{job}}"
    }
   ]
  },
  {
   "title": "Estimated total number of keys",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[table]]_estimated_num_keys) by (job)",
     "legendFormat": "keys-{{job}}"
    }
   ]
  },
  {
   "title": "Number of live versions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[table]]_num_live_versions) by (job)",
     "legendFormat": "versions-{{job}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[table]]_estimated_table_readers_mem) by (job)",
     "legendFormat": "table_readers-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_block_cache_usage) by (job)",
     "legendFormat": "block_cache-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_block_cache_pinned_usage) by (job)",
     "legendFormat": "block_cache_pinned-{{job}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[table]]_estimated_live_data_size) by (job)",
     "legendFormat": "live_data-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_total_sst_files_size) by (job)",
     "legendFormat": "total_sst-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_total_live_sst_files_size) by (job)",
     "legendFormat": "total_live_sst-{{job}}"
    },
    {
     "expr": "sum(qed_[[table]]_estimated_pending_compaction_bytes) by (job)",
     "legendFormat": "pending_compactions-{{job}}"
    }
   ]
  },
  {
   "title": "Actual delayed write rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_[[table]]_actual_delayed_write_rate) by (job)",
     "legendFormat": "delayed-{{job}}"
    }
   ]
  }
 ]
}