{
 "title": "Storage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Block cache hits and misses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_block_cache_hit) by (job)",
     "legendFormat": "hit_{{job}}"
    },
    {
     "expr": "sum(qed_storage_block_cache_miss) by (job)",
     "legendFormat": "miss_{{job}}"
    }
   ]
  },
  {
   "title": "Block cache bloom filter effectiveness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_filter_useful) by (job)",
     "legendFormat": "useful{{job}}"
    },
    {
     "expr": "sum(qed_storage_filter_full_positive) by (job)",
     "legendFormat": "full_positive{job}}"
    },
    {
     "expr": "sum(qed_storage_filter_full_true_positive) by (job)",
     "legendFormat": "full_true_positive{job}}"
    }
   ]
  },
  {
   "title": "Block cache add and add failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_block_cache_add) by (job)",
     "legendFormat": "add_{{job}}"
    },
    {
     "expr": "sum(qed_storage_block_cache_add_failures) by (job)",
     "legendFormat": "miss_{{job}}"
    }
   ]
  },
  {
   "title": "Block cache memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_block_cache_memory_usage) by (job)",
     "legendFormat": "bytes{{job}}"
    },
    {
     "expr": "sum(qed_storage_block_cache_pinned_memory_usage) by (job)",
     "legendFormat": "bytes_pinned{{job}}"
    }
   ]
  },
  {
   "title": "Block cache bytes read and written",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_block_cache_bytes_read) by (job)",
     "legendFormat": "bytes_read{{job}}"
    },
    {
     "expr": "sum(qed_storage_block_cache_bytes_write) by (job)",
     "legendFormat": "bytes_written{{job}}"
    }
   ]
  },
  {
   "title": "Memtable hits and misses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_memtable_hit) by (job)",
     "legendFormat": "hit{{job}}"
    },
    {
     "expr": "sum(qed_storage_memtable_miss) by (job)",
     "legendFormat": "miss{{job}}"
    }
   ]
  },
  {
   "title": "IO keys read, written and updated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_io_keys_read) by (job)",
     "legendFormat": "read{{job}}"
    },
    {
     "expr": "sum(qed_storage_io_keys_written) by (job)",
     "legendFormat": "written{{job}}"
    },
    {
     "expr": "sum(qed_storage_io_keys_updated) by (job)",
     "legendFormat": "updated{{job}}"
    }
   ]
  },
  {
   "title": "Get hits per level",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_get_hits_l0) by (job)",
     "legendFormat": "hit_l0{{job}}"
    },
    {
     "expr": "sum(qed_storage_get_hits_l1) by (job)",
     "legendFormat": "hit_l1{{job}}"
    },
    {
     "expr": "sum(qed_storage_get_hits_l2_up) by (job)",
     "legendFormat": "hit_l2_and_up{{job}}"
    }
   ]
  },
  {
   "title": "IO wait in compaction or flush",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_io_stall_micros) by (job)",
     "legendFormat": "bytes_read{{job}}"
    }
   ]
  },
  {
   "title": "IO bytes read and written",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_io_bytes_read) by (job)",
     "legendFormat": "read_{{job}}"
    },
    {
     "expr": "sum(qed_storage_io_bytes_written) by (job)",
     "legendFormat": "write_{{job}}"
    }
   ]
  },
  {
   "title": "WAL files synced",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_io_wal_files_synced) by (job)",
     "legendFormat": "files_synced{{job}}"
    }
   ]
  },
  {
   "title": "WAL bytes written",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_io_wal_file_bytes) by (job)",
     "legendFormat": "bytes{{job}}"
    }
   ]
  },
  {
   "title": "IO: compaction: bytes read, written and flushed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_io_compact_read_bytes) by (job)",
     "legendFormat": "read{{job}}"
    },
    {
     "expr": "sum(qed_storage_io_compact_write_bytes) by (job)",
     "legendFormat": "written{{job}}"
    },
    {
     "expr": "sum(qed_storage_io_compact_flush_bytes) by (job)",
     "legendFormat": "flushed{{job}}"
    }
   ]
  },
  {
   "title": "Block compression",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_storage_compress_block_compressed) by (job)",
     "legendFormat": "compressed{{job}}"
    },
    {
     "expr": "sum(qed_storage_compress_block_decompressed) by (job)",
     "legendFormat": "decompressed{{job}}"
    },
    {
     "expr": "sum(qed_storage_compress_block_not_compressed) by (job)",
     "legendFormat": "not_compressed{{job}}"
    }
   ]
  },
  {
   "title": "IO ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_disk_io_now) by (job,device)",
     "legendFormat": "ops{{job}}@{{device}}"
    }
   ]
  },
  {
   "title": "IO reads and writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total[30s])) by (job,device)",
     "legendFormat": "reads{{job}}@{{device}}"
    }
   ]
  }
 ]
}