# Build customization
env: 
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_LDFLAGS_ALLOW=".*"
      - GOOS=linux
    binary: qed
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X github.com/bbva/qed/build.tag={{.Tag}} -X github.com/bbva/qed/build.rev={{.FullCommit}} -X github.com/bbva/qed/build.utcTime={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archive:
  wrap_in_directory: true
  files:
    - README.md
    - LICENSE
release:
  github:
    owner: bbva
    name: qed
changelog:
  skip: true
dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
    - qed
    image_templates:
    - "bbvalabs/qed:latest"
    - "bbvalabs/qed:{{ .Tag }}"
    skip_push: auto
    dockerfile: Dockerfile 
  

