# Build customization
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
      - GOOS=linux
      - GO111MODULE=on
    binary: qed
    goos:
      - linux
    goarch:
      - amd64
archive:
  files:
    - README.md
    - LICENSE
