# Build customization
env: 
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_LDFLAGS_ALLOW=".*"
      - GOOS=linux
    binary: qed
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archive:
  wrap_in_directory: true
  files:
    - README.md
    - LICENSE
release:
  github:
    owner: bbva
    name: qed
changelog:
  skip: true
dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
    - qed
    image_templates:
    - "bbvalabs/qed:latest"
    - "bbvalabs/qed:{{ .Tag }}"
    skip_push: auto
    dockerfile: Dockerfile 
  

