#!/bin/bash

function _readlink() { (
  # INFO: readlink does not exists on OSX ¯\_(ツ)_/¯
  cd $(dirname $1)
  echo $PWD/$(basename $1)
) }

# Deployment options
CGO_LDFLAGS_ALLOW='.*'
QED="go run $GOPATH/src/github.com/bbva/qed/main.go"

pub=$(_readlink /var/tmp/certs)
tdir=$(mktemp -d /tmp/qed_build.XXX)
mkdir -p $pub
sign_path=${pub}
cert_path=${pub}/server.crt
key_path=${pub}/server.key

(
cd ${tdir}

if [ ! -f ${sign_path} ]; then
    #build shared signing key
    $QED generate signerkeys --path ${sign_path}
fi

if [ ! -f ${cert_path} ] && [ ! -f ${key_path} ]; then

    #build shared server cert
    openssl req \
        -newkey rsa:2048 \
        -nodes \
        -days 3650 \
        -x509 \
        -keyout ca.key \
        -out ca.crt \
        -subj "/CN=*"
    openssl req \
        -newkey rsa:2048 \
        -nodes \
        -keyout server.key \
        -out server.csr \
        -subj "/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=*"
    openssl x509 \
        -req \
        -days 365 \
        -sha256 \
        -in server.csr \
        -CA ca.crt \
        -CAkey ca.key \
        -CAcreateserial \
        -out server.crt \
        -extfile <(echo subjectAltName = IP:127.0.0.1)

    cp server.crt ${cert_path}
    cp server.key ${key_path}

fi

)
