#!/usr/bin/env sh

# Copyright 2018 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

lines=$(tput lines)
columns=$(tput cols)

if [ $# -ne 1 ]; then
    echo "Usage: $0 results_dir"
    exit 1
fi


dir="$1"
metric="$2"

if [ ! -z "$(find "$dir" -name '*pb.gz' -newer /tmp/data)" ]; then
    echo -n 'Refreshing /tmp/data...'
    for prof in $(find $dir -type f -name "*.pb.gz" | sort)
    do
        x=$(echo $prof | cut -d- -f2)
        go tool pprof -top -unit ms "$prof" | awk '/%.*%.*%/ && NF == 6' | sed "s/^/$x /"
    done | awk '
     { sub("ms", "", $2);
       sub("ms", "", $5);
       sub("%", "", $3);
       sub("%", "", $6);
       print }
    ' | sort -k7,7 -k1,1n > /tmp/data
    echo 'done.'
else
    echo 'Using cached /tmp/data.'
fi

while dialog --separate-output                                                                \
             --buildlist 'Choose functions'                                                   \
             $lines $columns $lines                                                           \
             $(cat /tmp/data | awk '{ print $7 }' | sort -u | awk '{ print $0, $0, "off" }')  \
             2> /tmp/functions
do
    while dialog --radiolist                    \
                 'Choose field'                 \
                 12 20 5                        \
                 1 flat  on                     \
                 2 flat% off                    \
                 3 sum% off                     \
                 4 cum off                      \
                 5 cum% off                     \
                 2> /tmp/field
    do
        field=$(expr $(cat /tmp/field) + 1 )
        case $field in
            2|5)
                unit=ms
                ;;

            3|4|6)
                unit=%
                ;;

            *)
                ;;
        esac


        plots=$(
            for func_name in $(cat /tmp/functions)
            do
                echo \"\< awk \'\$7 == \\\"$func_name\\\"\' /tmp/data\" using 1:$field with lines title \"$func_name\",
            done
        )
        gnuplot -e "
                set terminal dumb size $columns $lines enhanced ansi256;
                set title '$func_name';
                set xlabel '# of events';
                set y2label '$unit';
                plot $plots;
                pause -1;
        "
    done
done
