#!/usr/bin/env bash

# Copyright 2018 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

certs="$HOME/.ssh"
qed="go run $GOPATH/src/github.com/bbva/qed/main.go"
service="go run $GOPATH/src/github.com/bbva/qed/tests/gossip/test_service.go"


apikey() { echo "--apikey test_key"; }
nodeId() { echo "--node-id ${FUNCNAME[1]}_$1";}
path() { echo "--path $1";}
log() { echo "--log $1";}
keyPath() { echo "--keypath $certs/id_ed25519"; }
httpAddr() { echo "--http-addr 127.0.0.1:88`printf '%02d' $1`"; }
mgmtAddr() { echo "--mgmt-addr 127.0.0.1:87`printf '%02d' $1`"; }
metricsAddr() { echo "--metris-addr 127.0.0.1:86`printf '%02d' $1`";}
raftAddr() { echo "--raft-addr 127.0.0.1:85`printf '%02d' $1`"; }
gossipAddr() { echo "--gossip-addr 127.0.0.1:84`printf '%02d' $1`"; }
joinAddr() { echo "--join-addr 127.0.0.1:8700"; }
gossipJoinAddr() { echo "--gossip-join-addr 127.0.0.1:8400"; }
profiling() { echo "--profiling"; }
cert() { echo "--certificate $certs/server.crt"; }
certKey() { echo "--certificate-key $certs/server.key"; }
tempDir() { mktemp -d -p "/var/tmp"; }

bindAddr() { echo "--bind 127.0.0.1:8`printf '%d%02d' $1 $2`"; }
alertsUrls() { echo "--alertsUrls http://127.0.0.1:8888"; }
qedUrls() { echo "--qedUrls http://127.0.0.1:8800"; }
pubUrls() { echo "--pubUrl http://127.0.0.1:8888"; }

qedLeader() {
	dir=`tempDir`
	echo $qed `apikey` `path $dir` `nodeId 0` `keyPath` `gossipAddr 0` `log error` `cert` `certKey` `profiling`
}

qedFollower() {
	dir=`tempDir`
	echo $qed `apikey` `path $dir` `nodeId $1` `keyPath` `gossipAddr $1` `log error` `cert` `certKey` `httpAddr $1` `mgmtAddr $1` `metricsAddr $1` `raftAddr $1` `gossipAddr $1` `joinAddr` `gossipJoinAddr` `cert` `certKey``profiling`
}


agent() {
	type=$1; shift;
	portIndex=$1; shift
	id=$1; shift;
	echo $qed agent `alertsUrls` $type `apiKey` `log error` `bindAddr $portIndex $id``gossipJoinAddr` `quedUrls` `pubUrls` `nodeId $id`
}

auditor() {
	agent auditor 1 $1
}

monitor() {
	agent monitor 2 $1
}

publisher() {
	agent publisher 3 $1
}

service() {
	echo $service
}

run() {
	name=$1; shift;
	cmd=$1; shift;
	dir=$1; shift;
	$cmd 2>&1 > $dir/$name.log &
	echo $!
}

x=$1; shift
qedCluster=$1; shift;
monitors=$1; shift;
auditors=$1; shift;
publisers=$1; shift;


