#!/usr/bin/env sh

# Copyright 2018 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

qedGossipEndpoint="127.0.0.1:8400"
alertsStoreEndpoint="http://127.0.0.1:8888"
snapshotStoreEndpoint="http://127.0.0.1:8888"
qedHTTPEndpoint="http://127.0.0.1:8800"
QED="go run $GOPATH/src/github.com/bbva/qed/main.go"

for i in `seq 1 $1`;
do
    $QED agent \
		--alertsUrls $alertsStoreEndpoint  \
		auditor \
		-k key  \
		-l info \
		--bind 127.0.0.1:810$i  \
		--join $qedGossipEndpoint \
		--qedUrls $qedHTTPEndpoint  \
		--pubUrls $snapshotStoreEndpoint \
		--node auditor$i &
done 

for i in `seq 1 $2`;
do
    $QED agent \
		--alertsUrls $alertsStoreEndpoint  \
		monitor \
		-k key  \
		-l info \
		--bind 127.0.0.1:820$i  \
		--join $qedGossipEndpoint \
		--qedUrls $qedHTTPEndpoint  \
		--pubUrls $snapshotStoreEndpoint \
		--node monitor$i &
done 

for i in `seq 1 $3`;
do
    $QED agent \
		--alertsUrls $alertsStoreEndpoint  \
		publisher \
		-k key  \
		-l info \
		--bind 127.0.0.1:831$i  \
		--join $qedGossipEndpoint \
		--pubUrls $snapshotStoreEndpoint \
		--node publisher$i &
done 
