#!/usr/bin/env sh

# Copyright 2018 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function check_profiling { 
    while ps ux | grep [p]prof > /dev/null
    do
        echo "Waiting profiler task"
        sleep 1
    done
}

echo Cleanup...
if [ $(uname) == "Darwin" ]; then
    check_profiling
    killall main || exit 0
else
    check_profiling
    fuser -k -n tcp 8080 8081 8082 8083 8084 || true
fi
sleep 5
rm -rf /var/tmp/demo.*
rm -f /var/tmp/id_ed25519{,.pub}
echo done.

