#!/usr/bin/env sh

export GOMAXPROCS=128 
export GODEBUG=gctrace=1 
DBPATH=/var/tmp/memtest

if [ ! -d "$DBPATH" ]
then
  echo "$DBPATH must exist and have read/write permission."
  exit 1
fi

echo "Cleanup..."
rm -rf "$DBPATH"
echo done

echo "Stress time!"
go run memory/badger.go -p $DBPATH -d 60s 2>&1 | gcvis
echo done

