#!/usr/bin/env sh

# Copyright 2018 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

./start_server

echo Stress time!
go run attack_add/attack_add.go -w 100 -r 1000 -d 60s -k pepe -e http://localhost:8800/events > report.bin
cat report.bin | vegeta report
cat report.bin | vegeta plot > plot.html
echo done.

./stop_server