#!/usr/bin/env sh

# Copyright 2018 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo Create id_ed25519 key
ssh-keygen -t ed25519 -N '' -f /var/tmp/id_ed25519

echo Starting server...
go run ../main.go start -k pepe -p $(mktemp -d /var/tmp/demo.XXX) -y /var/tmp/id_ed25519 -l info &
echo done.

sleep 5

echo Stress time!
go run attack_add/attack_add.go -w 100 -r 1000 -d 60s -k pepe -e http://localhost:8080/events > report.bin
cat report.bin | vegeta report
cat report.bin | vegeta plot > plot.html
echo done.

echo Cleanup...
fuser -k -n tcp 8080
rm -rf /var/tmp/demo.*
rm /var/tmp/id_ed25519*
echo done.
