---
#  Copyright 2018-2019 Banco Bilbao Vizcaya Argentaria, S.A.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
- name: Copy Inmemory Storage Binary
  copy:
      dest: /var/qed/{{ item }}
      src: config_files/bin/{{ item }}
      mode: 0777
  with_items:
    - storage

- name: Create Inmemory Storage start script
  template:
    dest: /var/qed/{{ item }} 
    src: ../../templates/{{ item }}.j2
    force: true
    mode: 0775
  with_items:
    - storage-start.sh
    - storage-stop.sh

- name: Install Storage systemd service unit file
  template:
    dest: /etc/systemd/system/{{ item }}
    src: ../../templates/{{ item }}.j2
  with_items:
    - storage.service
  register: storage_unit

- name: Enable and run Storage service
  systemd:
    name: storage
    state: started
    enabled: yes
    daemon_reload: yes

- name: Restart Storage
  service:
    name: storage
    state: restarted
    daemon_reload: yes
  when: storage_unit.changed
