#!/usr/bin/env bash

#  Copyright 2018-2019 Banco Bilbao Vizcaya Argentaria, S.A.
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


# Starts a local test setup

export CGO_LDFLAGS_ALLOW='.*'

# Start Snapshot Store
xterm -hold -e "go run $GOPATH/src/github.com/bbva/qed/testutils/notifierstore.go" &

# Start QED Cluster with 3 nodes
./servers_start 2 >/dev/null

# xterm -hold -e "bash -c 'while [ ! -f /var/tmp/qed-pids/qed-log-2.pid ] ; do echo Waiting Cluster to start... && sleep 5 ; done'" &
xterm -hold -e "bash -c 'while ! tail -f /var/tmp/qed-log-0/server.log ; do sleep 5 ; done'" &
xterm -hold -e "bash -c 'while ! tail -f /var/tmp/qed-log-1/server.log ; do sleep 5 ; done'" &
xterm -hold -e "bash -c 'while ! tail -f /var/tmp/qed-log-2/server.log ; do sleep 5 ; done'" &

# Start Agent Monitor
xterm -hold -e "bash -c './agents_start monitor && while ! tail -f /var/tmp/agent-monitor-0/agent.log ; do sleep 3 ; done'" &

# Start Agent Publisher
xterm -hold -e "bash -c './agents_start publisher && while ! tail -f /var/tmp/agent-publisher-0/agent.log ; do sleep 3 ; done'" &

# Start Agent Auditor
xterm -hold -e "./agents_start auditor && bash -c 'while ! tail -f /var/tmp/agent-auditor-0/agent.log ; do sleep 3 ; done'" &
