#!/usr/bin/env bash

# Copyright 2018-2019 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "export PROFILING_RATE_HZ=30 (in seconds) env variable to set the default profiling delay. Default profiling rate is 30. Output: results/cpu|mem.pb.gz"
IP=$1
: ${IP:=127.0.0.1}
DIR=results/${IP}

check_profiling() {
    while ps ux | grep [p]prof > /dev/null
    do
        echo "Profiler running"
        sleep $PROFILING_RATE_HZ
    done
    echo "Profiler stopped"
}

profiler_cmd() {
    ELAPSED=0
    while curl -s -X POST http://${IP}:8800/healthcheck -H "Api-Key: "test_key"" 2>&1 > /dev/null ; do
        (BALLOON_VERSION=$(printf "%.0f\n" $(curl -s http://${IP}:8600/metrics|grep "qed_raft_balloon_version [0-9]"|cut -d' ' -f2))
        # Avoid empty version because preload process is not already started...
        : ${BALLOON_VERSION:=0}
        go tool pprof -proto -sample_index=alloc_objects -output ${DIR}/$(date +%s)-${BALLOON_VERSION}-mem-alloc-objects.pb.gz http://${IP}:6060/debug/pprof/heap
        go tool pprof -proto -sample_index=alloc_space -output ${DIR}/$(date +%s)-${BALLOON_VERSION}-mem-alloc-space-top.pb.gz http://${IP}:6060/debug/pprof/heap
        go tool pprof -proto -sample_index=inuse_objects -output ${DIR}/$(date +%s)-${BALLOON_VERSION}-mem-inuse-objects.pb.gz http://${IP}:6060/debug/pprof/heap
        go tool pprof -proto -sample_index=inuse_space -output ${DIR}/$(date +%s)-${BALLOON_VERSION}-mem-inuse-space-top.pb.gz http://${IP}:6060/debug/pprof/heap
        go tool pprof -proto -seconds 60 -output ${DIR}/$(date +%s)-${BALLOON_VERSION}-cpu-profile.pb.gz http://${IP}:6060) 2>&1 > /dev/null
        sleep $PROFILING_RATE_HZ
    done
}

: ${PROFILING_RATE_HZ:=30}
mkdir -p ${DIR}
echo "PROFILING_RATE_HZ=${PROFILING_RATE_HZ}s"
echo "IP=$IP"
profiler_cmd
check_profiling
