#!/usr/bin/env sh

# Copyright 2018 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo Create id_ed25519 key
ssh-keygen -t ed25519 -N '' -f /var/tmp/id_ed25519

echo Starting server...
/tmp/qed/cloud/aws/qed start -k pepe -p $(mktemp -d /var/tmp/demo.XXX) --raftpath $(mktemp -d /var/tmp/demo.XXX) -y /var/tmp/id_ed25519 -l info &
echo done.

sleep 10

echo Stress time!

wrk -t100 -c100 -d60s --latency -s /tmp/qed/attack_add/attack_add.lua http://localhost:8080 >> /tmp/"$(curl -s http://169.254.169.254/latest/meta-data/instance-type)-results.txt"
cat /proc/cpuinfo >> /tmp/"$(curl -s http://169.254.169.254/latest/meta-data/instance-type)-results.txt"
echo done.

echo Cleanup...
/sbin/fuser -k -n tcp 8080
rm -rf /var/tmp/demo.*
rm /var/tmp/id_ed25519
echo done.