{
 "title": "Hosts Monitoring",
 "description": "Docker Monitoring Template",
 "tags": [
  "prometheus, ",
  "node-exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Qeds",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=~\"Qed.*\"})/2"
    }
   ]
  },
  {
   "title": "Auditors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=~\"Auditor.*\"})/2"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=~\"Monitor.*\"})/2"
    }
   ]
  },
  {
   "title": "Publishers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=~\"Publisher.*\"})/2"
    }
   ]
  },
  {
   "title": "Store",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=~\"Store.*\"})/2"
    }
   ]
  },
  {
   "title": "workload",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=~\"workload.*\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(node_load1) by (job)", "legendFormat": "{{job}}-load1" }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=~\"Qed.*\"})/sum(qed_instances_count)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{job=~\"Qed.*\"} - node_filesystem_avail_bytes{job=~\"Qed.*\"}) by (job)",
     "legendFormat": "Used {{job}}"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"Qed.*\"})/sum(qed_instances_count)",
     "legendFormat": "Max-QED"
    },
    { "expr": "15*1024*1024*1024", "legendFormat": "Max-Agent" },
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (job)",
     "legendFormat": "Used {{job}}"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[$interval])) by (job)",
     "legendFormat": "recv-{{job}}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total[$interval])) by (job)",
     "legendFormat": "sent-{{job}}"
    }
   ]
  },
  {
   "title": "Read & Write Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total[30s])) by (job,device)",
     "legendFormat": "written-{{job}}@{{device}}"
    },
    {
     "expr": "-sum(rate(node_disk_read_bytes_total[30s])) by (job,device)",
     "legendFormat": "read-{{job}}@{{device}}"
    }
   ]
  }
 ]
}