{
 "title": "Raft internal",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Applied index",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qed_raft_internal_applied_index)",
     "legendFormat": "applied index"
    }
   ]
  },
  {
   "title": "FSM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_raft_internal_fsm_pending)",
     "legendFormat": "fsm_pending"
    }
   ]
  },
  {
   "title": "Commit index",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qed_raft_internal_commit_index)",
     "legendFormat": "commit index"
    }
   ]
  },
  {
   "title": "Snapshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Last index",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qed_raft_internal_last_snapshot_index)",
     "legendFormat": "last index"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qed_raft_internal_last_snapshot_index)",
     "legendFormat": "last_index"
    },
    {
     "expr": "sum(qed_raft_internal_last_snapshot_term)",
     "legendFormat": "last_term"
    }
   ]
  },
  {
   "title": "Last term",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qed_raft_internal_last_snapshot_term)",
     "legendFormat": "last term"
    }
   ]
  },
  { "title": "Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Last index",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qed_raft_internal_last_log_index)",
     "legendFormat": "last index"
    }
   ]
  },
  {
   "title": "Last term",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(qed_raft_internal_last_log_term)",
     "legendFormat": "last term"
    }
   ]
  }
 ]
}