{
 "title": "Riot",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Events added",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(riot_event_add)" }
   ]
  },
  {
   "title": "Adds failed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(riot_event_add_fail)" }
   ]
  },
  {
   "title": "Memberships",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(riot_query_membership)" }
   ]
  },
  {
   "title": "Incrementals",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(riot_query_incremental)" }
   ]
  }
 ]
}