#!/usr/bin/env sh

# Copyright 2018 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

case "$1" in
	leader)
		endpoint=http://localhost:8080
	;;
	follower1)
		endpoint=http://localhost:8081
	;;
	follower2)
		endpoint=http://localhost:8082
	;;
	*)
	echo "usage: $0 <leader|follower1|follower2>"
	exit 1
	;;
esac

go run ../../main.go										\
	-k pepe											\
	client											\
	--endpoint "$endpoint"									\
	incremental										\
	--end 8											\
	--endDigest ae3a5f42988aad598842ec3c3a4f929cfccd36377ffe72cd4783546b3087ea22		\
	--start 1										\
	--startDigest 900ef602f1d86eb98f4c86f166fa290046fc6aecca50acee3bc061280a60ba9c		\
	--verify										\
	-l info
