#!/usr/bin/env sh

# Copyright 2018-2019 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo 'Starting follower #2...'
go run ../../main.go start \
    -k test_key \
    -p $(mktemp -d /var/tmp/demo.XXX) \
    --raftpath /var/tmp/qed_ed25519 \
    -l debug \
    --http-addr :8802 \
    --mgmt-addr :8702 \
    --metrics-addr :8602 \
    --raft-addr :8502 \
    --gossip-addr :8402 \
    --join-addr :8700 \
    --node-id follower2
echo done.
