#!/usr/bin/env sh

# Copyright 2018-2019 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Deployment options
CGO_LDFLAGS_ALLOW='.*'
QED="go run $GOPATH/src/github.com/bbva/qed/main.go"

# build shared signing key
$QED generate keypair --path /var/tmp/id_ed25519

tdir=$(mktemp -d /var/tmp/demo.XXX)

echo 'Starting leader...'
go run $QED start \
    -k test_key \
    -p ${tdir} \
    --keypath /var/tmp/id_ed25519 \
    -l debug \
    --http-addr :8800 \
    --raft-addr :8500 \
    --mgmt-addr :8700
echo done.

echo Cleanup...
if [ $(uname) == "Darwin" ]; then
    pkill main
else
    fuser -k -n tcp 8800
fi

rm -rf /var/tmp/demo.*
rm -f /var/tmp/id_ed25519{,.pub}
echo done.
