---
#  Copyright 2018-2019 Banco Bilbao Vizcaya Argentaria, S.A.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
- name: Create workload start|stop script
  template:
    dest: /var/qed/{{ item }}
    src: ../../templates/{{ item }}.j2
    force: true
    mode: 0775
  with_items:
    - workload-start.sh

- name: Install workload systemd service unit file
  template:
    dest: /etc/systemd/system/{{ item }}
    src: ../../templates/{{ item }}.j2
  with_items:
    - workload.service
  register: workload_unit

- name: Enable and run workload service
  systemd:
    name: workload
    state: started
    enabled: yes
    daemon_reload: yes

- name: Restart workload
  service:
    name: workload
    state: restarted
    daemon_reload: yes
  when: workload_unit.changed
