#!/usr/bin/env sh

# Copyright 2018-2019 Banco Bilbao Vizcaya Argentaria, S.A.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Get developement tools and build Wrk
echo "Installing required stuff. Check logs at /tmp/yum_install.log"
sudo yum groupinstall 'Development Tools' -y >> /tmp/yum_install.log
sudo yum install -y openssl-devel git -y >> /tmp/yum_install.log

if [ ! -f /usr/bin/wrk ];
then
    echo "Building Wrk. Check logs at /tmp/wrk_make.log"
    git clone -q https://github.com/wg/wrk.git wrk >> /tmp/wrk_make.log
    cd wrk
    make >> /tmp/wrk_make.log
    # move the executable to somewhere in your PATH
    sudo cp wrk /usr/bin/wrk
fi